FROM ros:humble

SHELL ["/bin/bash", "-c"]

# Update to latest version
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="Europe/London"
RUN apt-get update

# install ros package
RUN apt-get update && apt-get install -y \
      ros-${ROS_DISTRO}-desktop \
      ros-${ROS_DISTRO}-demo-nodes-cpp \
      ros-${ROS_DISTRO}-demo-nodes-py \
      wget \
      python2.7

WORKDIR /root

RUN mkdir -p ~/plansys2_ws/src && \
    cd ~/plansys2_ws/src && \
    git clone https://github.com/IntelligentRoboticsLabs/ros2_planning_system.git

RUN cd ~/plansys2_ws/src/ros2_planning_system && \
    git clone https://github.com/PlanSys2/plansys2_tfd_plan_solver.git

RUN cd ~/plansys2_ws && rosdep install -y -r -q --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}

RUN cd ~/plansys2_ws/src && \
    git clone https://github.com/IntelligentRoboticsLabs/ros2_planning_system_examples.git

RUN cd ~/plansys2_ws && rosdep install -y -r -q --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}

RUN apt-get install -y vim gdb terminator

RUN cd ~/plansys2_ws && source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --symlink-install

# setup tfd
ENV TFD_HOME /root/tfd/
RUN mkdir -p $TFD_HOME
WORKDIR $TFD_HOME
RUN wget "http://gki.informatik.uni-freiburg.de/tools/tfd/downloads/version-0.4/tfd-src-0.4.tgz"
RUN tar xzf "tfd-src-0.4.tgz"
WORKDIR $TFD_HOME/tfd-src-0.4
RUN sed -e s/"-Werror"//g -i ./downward/search/Makefile
RUN ./build

RUN ln -s /usr/bin/python2.7 /usr/bin/python
RUN echo "export TFD_HOME=/root/tfd/tfd-src-0.4/downward/" >> ~/.bashrc

WORKDIR /root

CMD /bin/bash

# to build
# sudo docker build --rm  --tag ros-humble . --file Dockerfile-humble

# to run
# sudo docker run -v /tmp/.X11-unix/:/tmp/.X11-unix/ --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --network=host --name ubuntu_bash --env="DISPLAY" --rm -i -t ros-humble bash
